export const enum ExamplesTypes {
  HTTP_REQUEST = 'HTTP REQUEST',
  DOTENV_CONFIG = 'DOTENV CONFIG',
  YAML = 'YAML PARSER',
  MD = 'MARKDOWN PARSER',
  LINKEDOM = 'LINKEDOM PARSER',
  FORM_DATA = 'FORM DATA'
}
